[MISC] Fix CD workflow

diff --git a/templates/continous-delivery.yml.tmpl b/templates/continous-delivery.yml.tmpl
--- a/templates/continous-delivery.yml.tmpl
+++ b/templates/continous-delivery.yml.tmpl
@@ -1,10 +1,10 @@
-name: CI - Create a Release
+name: CD - Create a Release
 
-on:
-  push:
-    # Sequence of patterns matched against refs/tags
-    tags:
-      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
+on: [workflow_dispatch]
+#  push:
+#    # Sequence of patterns matched against refs/tags
+#    tags:
+#      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
 
 jobs:
   autorelease:
@@ -19,6 +19,12 @@ jobs:
         with:
           python-version: '{{PYTHON_VERSION}}'
 
+      - name: Build source and binary distributions
+        shell: bash -l {0}
+        run: |
+          python -m pip install build wheel
+          python setup.py sdist bdist_wheel
+
       - name: Add version to environment vars
         run: |
           PROJECT_VERSION=$(python setup.py --version)
@@ -31,14 +37,38 @@ jobs:
           echo $PROJECT_VERSION
           if [[ "$TAG" != "v$PROJECT_VERSION" ]]; then exit 1; fi
 
-      - name: Check typing, linting, formatting and run unit-tests
-        run: make checks
-
-      - name: Build distributions
-        shell: bash -l {0}
+      - name: Check source package structure
         run: |
-          python -m pip install build wheel
-          python setup.py sdist bdist_wheel
+          tar -xzf $(ls -rt  dist/*.tar.gz | tail -1)
+          DIR=$(python setup.py --fullname)
+          rm -rf $(find . -name "*.pyc") $(find . -name "__pycache__")
+          files=(
+            "requirements/requirements.txt"
+            "LICENSE"
+            "MANIFEST.in"
+            "PKG-INFO"
+            "README.md"
+            "setup.cfg"
+            "setup.py"
+            "versioneer.py"
+          )
+          while IFS= read -d $'\0' -r file ; do
+            if [[ "${file}" =~ .*".py" ]]; then files=("${files[@]}" "$file"); fi;
+          done < <(find cgnal -print0)
+
+          for file in "${files[@]}" ; do
+            if [ ! -f "${DIR}/${file}" ]; then echo "Missing ${file}"; exit 1; fi
+          done
+
+          rm -rf $DIR
+
+      - name: Check typing, linting and formatting
+        run: |
+          python -m pip install -r requirements/requirements_ci.txt
+          python -m black {{SRC}} tests
+          flake8 {{SRC}} tests
+          mypy --install-types --non-interactive --follow-imports silent {{SRC}} tests
+          python -m pytest
 
       - name: Release Notes
         uses: heinrichreimer/github-changelog-generator-action@v2.3
@@ -46,21 +76,33 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           output: ".github/RELEASE-TEMPLATE.md"
 
-      - name: Create Release
+      - name: Create Github Release
         uses: softprops/action-gh-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           body_path: ".github/RELEASE-TEMPLATE.md"
           files: |
-            dist/{{PROJECT_NAME}}-${{env.PROJECT_VERSION}}-py3-none-any.whl
-            dist/{{PROJECT_NAME}}-${{env.PROJECT_VERSION}}.tar.gz
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            dist/cgnal-core-${{env.PROJECT_VERSION}}-py3-none-any.whl
+            dist/cgnal-core-${{env.PROJECT_VERSION}}.tar.gz
 
       - name: Publish distribution to Test PyPI
         uses: pypa/gh-action-pypi-publish@master
         with:
           password: ${{ secrets.TESTPYPI_TOKEN }}
           repository_url: https://test.pypi.org/legacy/
+          skip_existing: true
+
+      - name: Test distribution published on Test PyPI
+        run: |
+          mkdir pkgs
+          make uninstall
+          sleep 5m
+          python -m pip download --index-url https://test.pypi.org/simple/ --no-deps --dest pkgs {{PROJECT_NAME}}==${{env.PROJECT_VERSION}}
+          python -m pip install $(ls -rt  pkgs/* | tail -1)
+          python -m pip install pytest pytest-cov mongomock
+          python -m pytest
+          rm -rf pkgs
 
       - name: Publish distribution to PyPI
         if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
